### ISSUE TITLE
Title 화면에 Scene 바로가기 기능 구현

### ISSUE THREAD

**Issue by ahnteve** [ddalpange/ssu-processing#12]
> 콘텐츠의 도입부에 씬(scene) 단위로 바로가기가 구현되어야함.

[팀 프로젝트 스펙](https://useful-pincushion-2c0.notion.site/Team-Projects-using-Processing-with-p5-js-90387570b3094bdfb6ef9c074615b462)에 기술된 내용입니다.

**Comment by penspanic** [comment]
완료했습니다~
