### ISSUE TITLE
SceneManager에 화면 전환 효과 추가하기

### ISSUE THREAD

**Issue by ahnteve** [ddalpange/ssu-processing#14]
- SceneManager에 Scene 전환 시 화면 전환 효과를 넣을 수 있는 기능을 추가합니다.
- 전환 효과는 컷(기본), 페이드, 디졸브 정도면 충분할 것 같습니다.

**Comment by ahnteve** [comment]
화면 전환 효과를 추가하기 위해서는 Scene의 실행 여부를 컨트롤할 수 있어야 할 것 같습니다.
ex) Scene1에서 Scene2로 전환될 때 페이드 효과를 적용하려면, Scene2의 초기 화면이 그려진 상태에서 페이드 인 효과가 끝난 후 Scene2가 시작되어야 함.

**Comment by penspanic** [comment]
씬 전환 도중에는 mousePressed등 Interaction이 안먹게 하는 등 추가 처리가 필요할 것 같구요,

실제로 페이드나 디졸브등 화면 효과는 PostProcessManager와 자체 제작 셰이더(glsl)를 사용해 구현하면 될 듯 합니다.

셰이더는 Main/Data/ 폴더내에 있는 기존 셰이더를 참고하면 됩니다.
