### ISSUE TITLE
대사재생기 개발

### ISSUE THREAD

**Issue by real0131** [ddalpange/ssu-processing#4]
# 내용
![i13934692725](https://github.com/ddalpange/ssu-processing/assets/12093323/09fae12e-02de-41ac-a692-2cfb756c812c)
그림 1 예시 이미지 

대사재생기 개발
씬 스크립트 작성 시 사용 할 수 있도록 클래스 형태로 개발
UI 표출까지 개발

# 메소드

## 대화창 노출
void show(void)

## 대화창 숨기기
void hide(void)

## 대화 (상황 설명등 화자가 필요없는경우)
void push(string msg)

## 대화 (화자가 있는 경우) 
void push(string msg, string teller)

## push 된 대화 전체 가져오기
string[] getAll(void)

## 이전에 표출된 대사 중 특정 대사로 이동
void move(int index)

간단하게 정리해보았는데 의견있으시면 편하게 부탁드립니다.

**Comment by penspanic** [comment]
전역 함수라면 이름이 좀더 구체적이어야 할 것 같습니다. showDialog, hideDialog, pushXXX 처럼요. 클래스내 메서드면 괜찮을 듯 합니다.
